CORCI-881 build: Backport certmonger to Leap-15
daos-stack/certmonger pull request #1
Opened 2020-03-11 19:14 UTC by JohnMalmberg

Backport an experimental build of certmonger to OpenSUSE Leap-15 as
this is needed for FreeIPA.

Signed-off-by: John E Malmberg <john.e.malmberg@intel.com>

2020-03-13 11:46 UTC, brianjmurrell requested changes
The pipeline was not run for this PR.

2020-03-13 11:46 UTC, brianjmurrell commented on Makefile
> +PATCHES += 0006-NSS-crypto-policy-sets-minimum-RSA-and-DSA-key-size-.patch
These shouldn't be needed with current [packaging](https://github.com/daos-stack/packaging/).

2020-03-13 11:46 UTC, brianjmurrell commented on Makefile
> +	curl -f -L -O '$(SOURCE).sig'
Seems like this would be a reasonable addition to [packaging](https://github.com/daos-stack/packaging/).

2020-03-13 11:46 UTC, brianjmurrell commented on packaging/Makefile
> +include Makefile_packaging.mk
This file isn't needed here.

2020-03-13 18:55 UTC, brianjmurrell approved these changes
Looks good.  Just don't forget the packaging repo updates so that all of the projects get the benefit.

2020-03-13 18:55 UTC, brianjmurrell commented on packaging/Makefile_distro_vars.mk
> +endif
Did this work?  If so, it should go to [packaging/](https://github.com/daos-stack/packaging/)

2020-03-13 18:55 UTC, brianjmurrell commented on packaging/Makefile_packaging.mk
> -endif
Ditto if this is the other half of the previous change and it worked.

2020-03-13 18:55 UTC, brianjmurrell commented on packaging/Makefile_packaging.mk
> +
Ditto for going to the packaging repo.

2020-03-16 15:05 UTC, JohnMalmberg commented on packaging/Makefile
> +include Makefile_packaging.mk
Missed removing it when copying current packaging directory.  Will be gone in next update.

2020-03-16 15:05 UTC, JohnMalmberg commented on Makefile
> +PATCHES += 0006-NSS-crypto-policy-sets-minimum-RSA-and-DSA-key-size-.patch
Removing

2020-03-16 15:05 UTC, JohnMalmberg commented on Makefile
> +	curl -f -L -O '$(SOURCE).sig'
I throught about that, but was not sure if this was just a one-off.

2020-03-16 15:39 UTC, merged